### PR TITLE
RIP-65: adds logging in LTI launch

### PR DESCRIPTION
**Pull request by lyttam**
https://jira-secure.berkeley.edu/browse/RIP-65

### CODE REVIEW

**Comment by johncrossman** [comment]
Linter error. Looks good otherwise.

**Comment by johncrossman** [comment]
@lyttam @pauline2k @mlincoln  - both Ripley and Squiggy PRs have failed this morning due to, `...error in smart_open setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.6.*' `.  Bad third-party metadata?!  My first thought is to downgrade `smart-open` to 4.1.2 and then create a Jira to upgrade to v5. Other ideas?

**Comment by pauline2k** [comment]
@johncrossman

The offending line in 4.2 source:
https://github.com/RaRe-Technologies/smart_open/blob/v4.2.0/setup.py#L90

Seems to be the same in 4.1.2:
https://github.com/RaRe-Technologies/smart_open/blob/v4.1.2/setup.py#L90

And given that neither has changed in ages, I wonder what has caused these to start failing. A change in the Travis env?

**Comment by johncrossman** [comment]
@pauline2k - I agree, very odd. @lyttam downgraded smart-open to 4.1.2 and Travis is green.

**Comment by pauline2k** [comment]
Weird. Silly Travis. I guess this unblocks us for now!

**Pull request merged**
