### PR TITLE
RIP-656, simplify configs and logic of BConnected.send_system_error_email

### PR DESCRIPTION
**Pull request by johncrossman**
https://jira-secure.berkeley.edu/browse/RIP-656

The bConnected integration is strictly about sending error-alert emails.

### CODE REVIEW

**Comment by pauline2k** [comment]
@johncrossman Does this new setup give us a way to not attempt sending an email when errors happen on local dev machines?

**Comment by johncrossman** [comment]
@pauline2k - Let me amend the PR to add a config to enable/disable.

**Comment by johncrossman** [comment]
PR amended. I recommend reviewing with `?w=1`

**Comment by johncrossman** [comment]
@pauline2k - this PR is ready for re-review :)

**Comment by pauline2k** [comment]
Red alert!!

**Pull request merged**
